apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-ephermal-notes-api
spec:
  hostnames:
    - notes.example.invalid
  parentRefs:
    - name: homelab-gw
      namespace: networking
      sectionName: https
