# k8s/apps/ephermal-notes-api/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-apps
resources:
  - ../../base
  - external-config.yaml

patches:
  - target:
      kind: HTTPRoute
      name: http-ephermal-notes-api
    path: httproute-patch.yaml
  - target:
      kind: Deployment
      name: ephermal-notes-api-deploy
    path: deploy-patch.yaml
