apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opensearch-admin-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-prod
  target:
    name: opensearch-admin-prod
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: kv/prod/opensearch
        property: admin_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opensearch-oidc-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-prod
  target:
    name: opensearch-oidc-prod
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: kv/prod/opensearch
        property: oidc_client_id
    - secretKey: client_secret
      remoteRef:
        key: kv/prod/opensearch
        property: oidc_client_secret
