apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

commonLabels:
  app.kubernetes.io/name: opensearch
  app.kubernetes.io/instance: opensearch-prod
  env: prod

resources: []

helmCharts:
  - name: opensearch
    repo: https://opensearch-project.github.io/helm-charts/
    version: "2.30.1"
    releaseName: opensearch
    namespace: observability
    includeCRDs: true
    valuesFile: values-prod.yaml
