apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-observability
resources:
  - external-secret.yaml

helmCharts:
  - name: opensearch
    repo: https://opensearch-project.github.io/helm-charts/
    version: "3.4.0"
    releaseName: opensearch
    namespace: prod-observability
    includeCRDs: true
    valuesFile: values-prod.yaml
