apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - ../../base
  - http-authentik.yaml

labels:
  - pairs:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/instance: authentik-dev
      env: dev

helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io
    version: "2025.10.2"
    releaseName: authentik
    namespace: auth
    includeCRDs: true
    valuesFile: values-dev.yaml