apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-minio-console
  namespace: networking
spec:
  parentRefs:
    - name: homelab-gw
      namespace: networking
      sectionName: http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /minio/
      backendRefs:
        - name: minio-console
          namespace: platform
          port: 9001
