apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ephermal-notes
  namespace: prod
spec:
  parentRefs:
    - name: homelab-gw
      namespace: networking
  hostnames: ["notes.example.com"]  # TODO: your real domain
  rules:
    - matches:
        - path: { type: PathPrefix, value: "/" }
      backendRefs:
        - name: ephermal-notes-api-service
          port: 80
