apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-n8n
  namespace: networking
spec:
  parentRefs:
    - name: homelab-gw
      namespace: networking
      sectionName: http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /n8n/
      backendRefs:
        - name: n8n
          namespace: platform
          port: 5678
