apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: personal-website
  namespace: prod
spec:
  parentRefs:
    - name: homelab-gw
      namespace: networking
  hostnames: ["bogdan.example.com"]  # TODO: your real domain
  rules:
    - matches:
        - path: { type: PathPrefix, value: "/" }
      backendRefs:
        - name: personal-website-ui
          port: 80
