apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: { name: traefik }
rules:
  - apiGroups: [""]
    resources: ["services","endpoints","secrets","namespaces"]
    verbs: ["get","list","watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get","list","watch"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gatewayclasses","gateways","httproutes","grpcroutes","tlsroutes","tcproutes","referencegrants"]
    verbs: ["get","list","watch","update","patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: { name: traefik }
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: networking
