apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-ephermal-notes-api
spec:
  parentRefs:
    - name: homelab-gw
      namespace: staging-networking
      sectionName: https
  hostnames:
    - notes.192-168-58-2.sslip.io
