apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-authentik
  namespace: networking
spec:
  parentRefs:
    - name: homelab-gw
      namespace: networking
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /auth/
      backendRefs:
        - name: authentik-server
          namespace: platform
          port: 80
