apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-seaweedfs-console
  namespace: networking
spec:
  parentRefs:
    - name: homelab-gw
      namespace: networking
      sectionName: https
  rules:
    - filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: authentik-forward-auth
      matches:
        - path:
            type: PathPrefix
            value: /seaweedfs/
      backendRefs:
        - name: seaweedfs-console
          namespace: platform
          port: 9001
