apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - gatewayclass.yaml
  - gateway.yaml
  - routes/http-ephermal-notes-api.yaml
  - routes/http-personal-website-ui.yaml
