apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-secrets
resources:
  - ../../base
  - clustersecretstore.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: "0.10.5"
    releaseName: external-secrets
    namespace: staging-secrets
    includeCRDs: true
    valuesFile: values-staging.yaml
