apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-ephermal-notes-api
spec:
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ephermal-notes-api-service
          port: 80
