apiVersion: v1
kind: Service
metadata:
  name: ephermal-notes-api-service
spec:
  type: ClusterIP
  selector:
    app: ephermal-notes-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
