apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-routes-to-shared-outpost
  namespace: staging-auth
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: staging-observability
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: staging-platform
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: staging-secrets
  to:
    - group: ""
      kind: Service
      name: ak-outpost-shared-outpost
