apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
spec:
  template:
    spec:
      containers:
        - name: redis-container
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-staging-secret
                  key: REDIS_PASSWORD
