apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-db
resources:
  - ../../base
  - external-secret.yaml

patches:
  - target:
      kind: Deployment
      name: redis-deploy
    path: deployment-patch.yaml
