apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: networking

commonLabels:
  app.kubernetes.io/name: traefik
  app.kubernetes.io/instance: traefik-dev
  env: dev

resources:
  - ../../base

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: "34.2.1"
    releaseName: traefik
    namespace: networking
    includeCRDs: true
    valuesFile: values-dev.yaml
