apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-networking
resources:
  - ../../base

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: "37.4.0"
    releaseName: traefik
    namespace: dev-networking
    includeCRDs: true
    valuesFile: values-dev.yaml
