fullnameOverride: fluent-bit-dev

kind: DaemonSet

image:
  repository: cr.fluentbit.io/fluent/fluent-bit
  tag: "3.0.4"

service:
  type: ClusterIP

config:
  service: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info
        Parsers_File /fluent-bit/etc/parsers.conf

        # Required for k8s liveness/readiness probes
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

  inputs: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            cri
        Tag               kube.*
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        
        # Disable inotify to prevent "too many open files"
        Inotify_Watcher   Off
        
        # File position tracking
        DB                /var/log/flb_kube.db
        DB.locking        true

  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        Kube_Tag_Prefix     kube.var.log.containers.

  outputs: |
    [OUTPUT]
        Name            opensearch
        Match           kube.*
        Host            opensearch-cluster-master.observability.svc.cluster.local
        Port            9200
        Index           logs-dev
        Type            _doc
        Logstash_Format On
        Suppress_Type_Name On
        Replace_Dots    On
        Retry_Limit     False

resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

podSecurityContext:
  runAsUser: 0

securityContext:
  privileged: true