apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-seaweedfs-public
spec:
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /public
          method: GET
        - path:
            type: PathPrefix
            value: /public
          method: HEAD
      backendRefs:
        - name: seaweedfs-s3
          port: 8333
