apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: networking

resources:
  - ../../base
  - routes/ui/http-personal-website-ui.yaml
  - routes/api/http-ephermal-notes-api.yaml
  - routes/platform/http-authentik.yaml
  - routes/platform/http-n8n.yaml
  - routes/platform/http-seaweedfs-console.yaml
  - routes/platform/http-grafana.yaml
  - routes/platform/http-opensearch-dashboards.yaml
