apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-secrets
resources:
  - ../../base

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: "0.10.5"
    releaseName: external-secrets
    namespace: dev-secrets
    includeCRDs: true
    valuesFile: values-dev.yaml
