apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-prod
  target:
    name: grafana-admin-prod
    creationPolicy: Owner
  data:
    - secretKey: grafana_admin
      remoteRef:
        key: kv/prod/grafana
        property: admin_user
    - secretKey: grafana_admin_password
      remoteRef:
        key: kv/prod/grafana
        property: admin_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-auth-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-prod
  target:
    name: grafana-auth-prod
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: kv/prod/grafana
        property: oidc_client_id
    - secretKey: client_secret
      remoteRef:
        key: kv/prod/grafana
        property: oidc_client_secret
