apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - ../../base

patches:
  - target:
      kind: HTTPRoute
      name: http-grafana
    path: httproute-patch.yaml

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: "8.5.10"
    releaseName: grafana
    namespace: observability
    includeCRDs: false
    valuesFile: values-prod.yaml
