apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

labels:
  - pairs:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: grafana-prod
      env: prod
    includeSelectors: true
    includeTemplates: true

resources: []

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: "8.5.10"
    releaseName: grafana
    namespace: observability
    includeCRDs: false
    valuesFile: values-prod.yaml
