apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-vault-ui
spec:
  parentRefs:
    - name: homelab-gw
      namespace: dev-networking
      sectionName: http
  hostnames:
    - vault.apps.192-168-58-2.sslip.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ak-outpost-shared-outpost
          namespace: dev-auth
          port: 9000
