apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-secrets
resources:
  - ../../base

patches:
  - target:
      kind: HTTPRoute
      name: http-vault-setup
    path: httproute-setup-patch.yaml
  - target:
      kind: HTTPRoute
      name: http-vault-ui
    path: httproute-ui-patch.yaml

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: "0.28.0"
    releaseName: vault
    namespace: dev-secrets
    includeCRDs: false
    valuesFile: values-dev.yaml
