- op: replace
  path: /spec/from
  value:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: staging-observability
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: staging-platform
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: staging-secrets
