apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secrets

resources:
  - ../../base
  - clustersecretstore.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: "0.10.5"
    releaseName: external-secrets
    namespace: secrets
    includeCRDs: true
    valuesFile: values-prod-dev.yaml
