apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - ../../base

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: "27.50.0"
    releaseName: prometheus
    namespace: observability
    includeCRDs: false
    valuesFile: values-prod.yaml

patches:
  - target:
      kind: HTTPRoute
      name: http-prometheus
    path: httproute-patch.yaml
