apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: personal-website-ui
  namespace: dev
spec:
  parentRefs:
    - name: homelab-gw
      namespace: networking
  hostnames:
    - homelab.10-102-79-188.sslip.io
  rules:
    - backendRefs:
        - name: personal-website-ui
          port: 80
