apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: personal-website-ui
  namespace: dev
spec:
  parentRefs:
    - name: homelab-gw
      namespace: networking
  hostnames: ["homelab.localtest.me"]
  rules:
    - matches: [{ path: { type: PathPrefix, value: "/" } }]
      backendRefs: [{ name: personal-website-ui, port: 80 }]
