apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ephermal-notes-api
  namespace: dev
spec:
  parentRefs:
    - name: homelab-gw
      namespace: networking
  hostnames: ["homelab.notes.api.localtest.me"]
  rules:
    - matches: [{ path: { type: PathPrefix, value: "/" } }]
      backendRefs: [{ name: ephermal-notes-api-service, port: 80 }]
