apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-personal-website-ui
  namespace: networking
spec:
  parentRefs:
    - name: homelab-gw
      namespace: networking
      sectionName: https
  hostnames:
    - my-cool-site.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: seaweedfs-filter
          namespace: platform
          port: 8888
