apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - ../../base
  - http-prometheus.yaml
  - ../../../../auth/authentik-forward-auth

labels:
  - pairs:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/instance: prometheus-dev
      env: dev
    includeSelectors: true
    includeTemplates: true

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: "27.50.0"
    releaseName: prometheus
    namespace: observability
    includeCRDs: false
    valuesFile: values-dev.yaml
