apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

commonLabels:
  app.kubernetes.io/name: prometheus
  app.kubernetes.io/instance: prometheus-dev
  env: dev

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: "27.0.0"
    releaseName: prometheus
    namespace: observability
    includeCRDs: false
    valuesFile: values-dev.yaml
