apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-seaweedfs-public
spec:
  parentRefs:
    - name: homelab-gw
      namespace: dev-networking
      sectionName: http
  hostnames:
    - storage.apps.192-168-58-2.sslip.io
