apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

resources:
  - ../../base
  - http-seaweedfs-dashboard.yaml
  - http-seaweedfs-public.yaml

labels:
  - pairs:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/instance: seaweedfs-dev
      env: dev
    includeSelectors: true
    includeTemplates: true

helmCharts:
  - name: seaweedfs
    repo: https://seaweedfs.github.io/seaweedfs/helm
    version: "4.0.392"
    releaseName: seaweedfs
    namespace: platform
    includeCRDs: true
    valuesFile: values-dev.yaml
