apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-grafana
  namespace: observability
spec:
  hostnames:
    - grafana.192-168-58-2.sslip.io
  parentRefs:
    - name: homelab-gw
      namespace: networking
      sectionName: http

  rules:
    # 1) Bypass ForwardAuth for authentik outpost endpoints (avoid loops)
    - matches:
        - path:
            type: PathPrefix
            value: /outpost.goauthentik.io/
      backendRefs:
        - name: ak-outpost-grafana-outpost
          namespace: auth
          port: 9000

    # 2) Protect Grafana with ForwardAuth middleware
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: authentik-forward-auth
      backendRefs:
        - name: grafana
          port: 80
