apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - ../../base
  - http-grafana.yaml
  - ../../../../auth/authentik-forward-auth

labels:
  - pairs:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: grafana-dev
      env: dev
    includeSelectors: true
    includeTemplates: true

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: "8.5.10"
    releaseName: grafana
    namespace: observability
    includeCRDs: false
    valuesFile: values-dev.yaml
