apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-prod-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-prod
  target:
    name: authentik-prod-creds
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: kv/prod/authentik
        property: secret_key
    - secretKey: AUTHENTIK_POSTGRESQL__HOST
      remoteRef:
        key: kv/prod/authentik
        property: postgresql_host
    - secretKey: AUTHENTIK_POSTGRESQL__PORT
      remoteRef:
        key: kv/prod/authentik
        property: postgresql_port
    - secretKey: AUTHENTIK_POSTGRESQL__NAME
      remoteRef:
        key: kv/prod/authentik
        property: postgresql_name
    - secretKey: AUTHENTIK_POSTGRESQL__USER
      remoteRef:
        key: kv/prod/authentik
        property: postgresql_user
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: kv/prod/authentik
        property: postgresql_password
    - secretKey: AUTHENTIK_REDIS__HOST
      remoteRef:
        key: kv/prod/authentik
        property: redis_host
    - secretKey: AUTHENTIK_REDIS__PORT
      remoteRef:
        key: kv/prod/authentik
        property: redis_port
    - secretKey: AUTHENTIK_REDIS__PASSWORD
      remoteRef:
        key: kv/prod/authentik
        property: redis_password
    - secretKey: AUTHENTIK_EMAIL__HOST
      remoteRef:
        key: kv/prod/authentik
        property: email_host
    - secretKey: AUTHENTIK_EMAIL__PORT
      remoteRef:
        key: kv/prod/authentik
        property: email_port
    - secretKey: AUTHENTIK_EMAIL__USERNAME
      remoteRef:
        key: kv/prod/authentik
        property: email_username
    - secretKey: AUTHENTIK_EMAIL__PASSWORD
      remoteRef:
        key: kv/prod/authentik
        property: email_password
    - secretKey: AUTHENTIK_EMAIL__FROM
      remoteRef:
        key: kv/prod/authentik
        property: email_from
    - secretKey: AUTHENTIK_EMAIL__USE_TLS
      remoteRef:
        key: kv/prod/authentik
        property: email_use_tls
    - secretKey: AUTHENTIK_EMAIL__USE_SSL
      remoteRef:
        key: kv/prod/authentik
        property: email_use_ssl
