apiVersion: v1
kind: Namespace
metadata:
  name: prod-auth
  labels:
    name: prod-auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-networking
  labels:
    name: prod-networking
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-cert-manager
  labels:
    name: prod-cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-observability
  labels:
    name: prod-observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-platform
  labels:
    name: prod-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-secrets
  labels:
    name: prod-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-apps
  labels:
    name: prod-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-db
  labels:
    name: prod-db
