apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-gw-tls
  namespace: staging-networking
spec:
  secretName: homelab-gw-tls
  issuerRef:
    kind: ClusterIssuer
    name: homelab-ca
  dnsNames:
    - "*.192-168-58-2.sslip.io"
    - "*.apps.192-168-58-2.sslip.io"
