apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-staging
spec:
  provider:
    vault:
      server: http://vault-active.staging-secrets.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: homelab-staging
          serviceAccountRef:
            name: external-secrets
            namespace: staging-secrets
