apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-ephermal-notes-api
  namespace: dev
spec:
  parentRefs:
    - name: homelab-gw
      namespace: networking
      sectionName: http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/notes
        - path:
            type: PathPrefix
            value: /swagger 
      backendRefs:
        - name: ephermal-notes-api-service
          port: 80
