# k8s/apps/ephermal-notes-api/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - http-ephermal-notes-api.yaml

configMapGenerator:
  - name: ephermal-notes-api-config
    literals:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - REDIS_ADDR=redis-service.dev-db.svc.cluster.local:6379
generatorOptions:
  disableNameSuffixHash: true
