apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homelab-gw
  namespace: networking
spec:
  listeners:
    - name: http
      protocol: HTTP
      port: 8000
      allowedRoutes:
        namespaces:
          from: All
    # - name: https
    #   protocol: HTTPS
    #   port: 8443
    #   tls:
    #     mode: Terminate
    #     certificateRefs:
    #       - kind: Secret
    #         name: homelab-gw-tls
    #         namespace: networking
    #   allowedRoutes:
    #     namespaces:
    #       from: All
