apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-networking
resources:
  - ../../base

patches:
  - target:
      kind: Gateway
      name: homelab-gw
    path: gateway-patch.yaml
