apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: networking

resources:
  - ../../base
  - routes/http-personal-website-ui.yaml
  - routes/http-ephermal-notes-api.yaml
  - routes/http-authentik.yaml
  - routes/http-n8n.yaml
  - routes/http-minio-console.yaml
  - routes/http-grafana.yaml
  - routes/http-opensearch-dashboards.yaml
