apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

commonLabels:
  app.kubernetes.io/name: n8n
  app.kubernetes.io/instance: n8n-dev
  env: dev

helmCharts:
  - name: n8n
    repo: https://community-charts.github.io/helm-charts
    version: "1.16.9"
    releaseName: n8n
    namespace: platform
    includeCRDs: true
    valuesFile: values-dev.yaml
