apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

resources:
  - ../../base
  - http-n8n.yaml
  - ../../../../auth/authentik-forward-auth

helmCharts:
  - name: n8n
    repo: https://community-charts.github.io/helm-charts
    version: "1.16.10"
    releaseName: n8n
    namespace: platform
    includeCRDs: true
    valuesFile: values-dev.yaml
