apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace-cert-manager.yaml
  - clusterissuer-selfsigned.yaml
  - certificate-ca.yaml
  - clusterissuer-homelab.yaml
  - certificate-gateway.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: "v1.15.1"
    releaseName: cert-manager
    namespace: prod-cert-manager
    includeCRDs: true
