apiVersion: v1
kind: Namespace
metadata:
  name: dev-auth
  labels:
    name: dev-auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-networking
  labels:
    name: dev-networking
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-observability
  labels:
    name: dev-observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-platform
  labels:
    name: dev-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-secrets
  labels:
    name: dev-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-apps
  labels:
    name: dev-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-db
  labels:
    name: dev-db
