apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-seaweedfs-console
  namespace: networking
spec:
  parentRefs:
    - name: homelab-gw
      namespace: networking
      sectionName: http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /seaweed/
      backendRefs:
        - name: seaweedfs-filer
          namespace: platform-seaweedfs
          port: 8888
