apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-observability
resources:
  - external-secret.yaml

helmCharts:
  - name: fluent-bit
    repo: https://fluent.github.io/helm-charts
    version: "0.54.0"
    releaseName: fluent-bit
    namespace: prod-observability
    includeCRDs: false
    valuesFile: values-prod.yaml
