apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources: []

helmCharts:
  - name: fluent-bit
    repo: https://fluent.github.io/helm-charts
    version: "0.46.7"
    releaseName: fluent-bit
    namespace: observability
    includeCRDs: false
    valuesFile: values-prod.yaml
