apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-staging
  target:
    name: postgresql-staging-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: kv/staging/authentik
        property: postgresql_name
    - secretKey: POSTGRES_USER
      remoteRef:
        key: kv/staging/authentik
        property: postgresql_user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: kv/staging/authentik
        property: postgresql_password
    - secretKey: N8N_PASSWORD
      remoteRef:
        key: kv/staging/n8n
        property: postgres_password
