apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-db
resources:
  - ../../base
  - external-secret.yaml
  - config-map.yaml

patches:
  - path: delete-secret.yaml
  - path: delete-configmap.yaml
