apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-db
resources:
  - ../../base
  - external-secret.yaml

patches:
  - target:
      kind: Deployment
      name: postgresql-deploy
    path: deployment-patch.yaml
  - target:
      kind: ConfigMap
      name: postgresql-init-sql
    path: configmap-patch.yaml
