apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fluent-bit-opensearch-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-staging
  target:
    name: fluent-bit-opensearch-staging
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: kv/staging/fluent-bit
        property: opensearch_username
    - secretKey: password
      remoteRef:
        key: kv/staging/fluent-bit
        property: opensearch_password
