apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-staging
  target:
    name: grafana-admin-staging
    creationPolicy: Owner
  data:
    - secretKey: grafana_admin
      remoteRef:
        key: kv/staging/grafana
        property: admin_user
    - secretKey: grafana_admin_password
      remoteRef:
        key: kv/staging/grafana
        property: admin_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-auth-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-staging
  target:
    name: grafana-auth-staging
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: kv/staging/grafana
        property: oidc_client_id
    - secretKey: client_secret
      remoteRef:
        key: kv/staging/grafana
        property: oidc_client_secret
