apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-postgres-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-prod
  target:
    name: n8n-postgres-prod
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: kv/prod/n8n
        property: postgres_password
    - secretKey: postgres-password
      remoteRef:
        key: kv/prod/n8n
        property: postgres_password
    - secretKey: postgresql-password
      remoteRef:
        key: kv/prod/n8n
        property: postgres_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-redis-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-prod
  target:
    name: n8n-redis-prod
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: kv/prod/n8n
        property: redis_password
    - secretKey: redis-password
      remoteRef:
        key: kv/prod/n8n
        property: redis_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-encryption-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-prod
  target:
    name: n8n-encryption-prod
    creationPolicy: Owner
  data:
    - secretKey: encryptionKey
      remoteRef:
        key: kv/prod/n8n
        property: encryption_key
    - secretKey: encryption_key
      remoteRef:
        key: kv/prod/n8n
        property: encryption_key
