apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-n8n
spec:
  hostnames:
    - n8n.example.invalid
  parentRefs:
    - name: homelab-gw
      namespace: prod-networking
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ak-outpost-shared-outpost
          namespace: prod-auth
          port: 9000
