apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-dev
spec:
  provider:
    vault:
      server: http://vault-active.dev-secrets.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: homelab-dev
          serviceAccountRef:
            name: external-secrets
            namespace: dev-secrets
