apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-vault-setup
spec:
  parentRefs:
    - name: homelab-gw
      namespace: staging-networking
      sectionName: https
  hostnames:
    - vault-setup.apps.192-168-76-2.sslip.io
