apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

commonLabels:
  app.kubernetes.io/name: minio
  app.kubernetes.io/instance: minio-dev
  env: dev

helmCharts:
  - name: minio
    repo: https://charts.bitnami.com/bitnami
    version: "17.0.21"
    releaseName: minio
    namespace: platform
    includeCRDs: true
    valuesFile: values-dev.yaml
