mode: standalone

auth:
  rootUser: "minio-dev-root"
  rootPassword: "minio-dev-password"
  forcePassword: true
  usePasswordFiles: true
  useSecret: true

  defaultBuckets: "personal-website, logs"

persistence:
  enabled: true
  size: 5Gi
  # storageClass: ""         # set if your cluster requires a specific class

resourcesPreset: "micro" 

service:
  type: ClusterIP
  ports:
    api: 9000

consoleService:
  type: ClusterIP
  port: 9001

tls:
  enabled: false
